### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by geoffraeder** [execonline-inc/antivirus#2]
First, thanks for putting this together.  I think it's going to solve our needs.  I believe I have everything configured correctly but getting this exception when I run index.js just after freshclam runs.  Any thoughts?  Thanks in advance.

`2016-08-26T00:54:14.676Z:  Error! TypeError: Cannot read property 'map' of undefined
    at /home/geoff/antivirus/node_modules/ramda/dist/ramda.js:3911:31
    at /home/geoff/antivirus/node_modules/ramda/dist/ramda.js:178:28
    at f1 (/home/geoff/antivirus/node_modules/ramda/dist/ramda.js:156:27)
    at /home/geoff/antivirus/node_modules/ramda/dist/ramda.js:384:22
    at /home/geoff/antivirus/node_modules/ramda/dist/ramda.js:384:35
    at f1 (/home/geoff/antivirus/node_modules/ramda/dist/ramda.js:156:27)
    at details (/home/geoff/antivirus/lib/s3promises.js:54:5)
    at /home/geoff/antivirus/node_modules/ramda/dist/ramda.js:384:35
    at f1 (/home/geoff/antivirus/node_modules/ramda/dist/ramda.js:156:27)
    at tryCatcher (/home/geoff/antivirus/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/geoff/antivirus/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/geoff/antivirus/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/geoff/antivirus/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/geoff/antivirus/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/geoff/antivirus/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/geoff/antivirus/node_modules/bluebird/js/main/async.js:15:14)`

**Comment by kofno** [comment]
Looks like it might not be handling the message from S3 properly. Do you have an example of the JSON you are getting?

**Comment by geoffraeder** [comment]
Thanks.  The message it's breaking on looks like this.  I'm not sure what "TestEvent" is.  I confirmed it is receiving proper record messages when files are created.

{
    "Bucket": "integrate-files.truqcapp.com",
    "Event": "s3:TestEvent",
    "HostId": "s/yK2JES6I881+6PuPk3EbGV5w0UI3h+l+zmTKW9CoXs45obUsGxAiA/5g0KCnZt",
    "RequestId": "13E685396168E0C6",
    "Service": "Amazon S3",
    "Time": "2016-08-26T13:37:58.695Z"
}

**Comment by geoffraeder** [comment]
I went and purged the queue, which I think may have addressed the issue. Thanks.

**Comment by kofno** [comment]
The test event is fired when you first configure notification on a bucket. Once you're setup, you shouldn't see those anymore. But we should handle that gracefully in the application.
