### ISSUE TITLE
Error! SyntaxError: Unexpected token u in JSON

### ISSUE THREAD

**Issue by dragosrosculete** [execonline-inc/antivirus#6]
So I have set it up but as soon as I upload a file to S3 , it gets sent to SQS, and the JS take the file it returns this error in the console : 

```
2017-02-23T08:17:56.591Z:  Error! SyntaxError: Unexpected token u in JSON at position 0
    at parse (<anonymous>)
    at /home/ubuntu/antivirus/node_modules/ramda/dist/ramda.js:384:22
    at f1 (/home/ubuntu/antivirus/node_modules/ramda/dist/ramda.js:156:27)
    at /home/ubuntu/antivirus/node_modules/ramda/dist/ramda.js:384:35
    at /home/ubuntu/antivirus/node_modules/ramda/dist/ramda.js:384:35
    at /home/ubuntu/antivirus/node_modules/ramda/dist/ramda.js:384:35
    at f1 (/home/ubuntu/antivirus/node_modules/ramda/dist/ramda.js:156:27)
    at details (/home/ubuntu/antivirus/lib/s3promises.js:54:5)
    at /home/ubuntu/antivirus/node_modules/ramda/dist/ramda.js:384:35
    at f1 (/home/ubuntu/antivirus/node_modules/ramda/dist/ramda.js:156:27)
    at tryCatcher (/home/ubuntu/antivirus/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/antivirus/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/ubuntu/antivirus/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/ubuntu/antivirus/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/ubuntu/antivirus/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/ubuntu/antivirus/node_modules/bluebird/js/main/async.js:133:10)
2017-02-23T08:17:56.592Z:  Error! SYNTAX ERROR - deleting message: {"MessageId":"5025e755-3c56-491b-9909-e3987d541463","ReceiptHandle":"AAAA/BBB","MD5OfBody":"8152f9e27646b37dc1053a36866e5467","Body":"{\"Records\":[{\"eventVersion\":\"2.0\",\"eventSource\":\"aws:s3\",\"awsRegion\":\"ap-southeast-2\",\"eventTime\":\"2017-02-23T08:17:56.501Z\",\"eventName\":\"ObjectCreated:Put\",\"userIdentity\":{\"principalId\":\"AWS:AAA\"},\"requestParameters\":{\"sourceIPAddress\":\"111.111.111.111\"},\"responseElements\":{\"x-amz-request-id\":\"64EFC8DD54C1C023\",\"x-amz-id-2\":\"AAA\"},\"s3\":{\"s3SchemaVersion\":\"1.0\",\"configurationId\":\"339aab74-9fa4-443c-8ccf-f79fd552b615\",\"bucket\":{\"name\":\"clamavtest.ABC.com\",\"ownerIdentity\":{\"principalId\":\"AAAA\"},\"arn\":\"arn:aws:s3:::clamavtest.ABC.com\"},\"object\":{\"key\":\"application\",\"size\":56,\"eTag\":\"d1fa60a253ba9bd5f70dfc6fafcb5e51\",\"sequencer\":\"0058AE9AB46F8435EC\"}}}]}"}
2017-02-23T08:17:56.593Z:  [ undefined ]
```

What is wrong, where is the problem ? I have checked the Json and it is valid

**Comment by kofno** [comment]
Most likely because the scanner is receiving an unexpected JSON document, or the payload we are actually trying to parse in in a different field then we are looking for. 

The parse error is because the scanner is trying to parse `undefined`.

**Comment by EstebanMarin** [comment]
I've seen something like this to fix the error:
` let data = JSON.parse(json.data || '{}');`

**Comment by aobriengreentube** [comment]
Hi, I have been doing some automation tests for the past few days but have no prior experience with coding so I am a complete newbie. I've attempted your fix in my code but when I run the test I get "ReferenceError: json is not defined". How do I define the json?
